version: '3.8'

services:
  service1:
    build: ./service_1
    container_name: golang_app
    expose:
      - 8001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://44.212.40.24:8001/ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  service2:
    build: ./service_2
    container_name: python_app
    expose:
      - 8002
    healthcheck:
      test: ["CMD", "curl", "-f", "http://44.212.40.24:8002/ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    build: ./nginx
    ports:
      - "8081:80"  
    depends_on:
      - service1
      - service2

